/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'featured' : IDL.Null,
  'mainstream' : IDL.Null,
  'onchain' : IDL.Null,
  'open_source' : IDL.Null,
});
export const ModelInput = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
  'category' : Category,
});
export const Model = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  'addModel' : IDL.Func([ModelInput], [], []),
  'getAllModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
  'getModelsByCategory' : IDL.Func([Category], [IDL.Vec(Model)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'featured' : IDL.Null,
    'mainstream' : IDL.Null,
    'onchain' : IDL.Null,
    'open_source' : IDL.Null,
  });
  const ModelInput = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
    'category' : Category,
  });
  const Model = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    'addModel' : IDL.Func([ModelInput], [], []),
    'getAllModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
    'getModelsByCategory' : IDL.Func([Category], [IDL.Vec(Model)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };