import type { AIModel, OSCategory, OSModel, Page } from "./types";

const _WM = "https://upload.wikimedia.org/wikipedia/commons";

export const AI_MODELS: AIModel[] = [
  {
    id: "claude",
    name: "Claude",
    company: "Anthropic",
    desc: "Anthropic's thoughtful AI — safe, helpful, and remarkably capable.",
    url: "https://claude.ai",
    color: "#CC785C",
    initials: "Cl",
    logo: "/assets/uploads/claude-ai-icon-019d21d9-5604-75eb-b393-5b31129f9f9b-1.webp",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    company: "OpenAI",
    desc: "OpenAI's flagship model — the AI that started the revolution.",
    url: "https://chat.openai.com",
    color: "#10A37F",
    initials: "GP",
    logo: "/assets/uploads/chatgpt-icon-019d21d9-5615-7798-92cb-63d62ac38dca-2.webp",
  },
  {
    id: "gemini",
    name: "Gemini",
    company: "Google",
    desc: "Google's multimodal AI — see, hear, and reason across modalities.",
    url: "https://gemini.google.com",
    color: "#4285F4",
    initials: "Gm",
    logo: "/assets/uploads/google-gemini-icon-019d21d9-5631-736f-985f-4fbe72d2df9d-3.webp",
  },
  {
    id: "llama",
    name: "Llama",
    company: "Meta",
    desc: "Meta's powerful open-source LLM family.",
    url: "https://llama.meta.com",
    color: "#0081FB",
    initials: "Ll",
    logo: "/assets/uploads/llama-meta-019d21fe-c59e-7432-9116-06df391a9e60-5.webp",
  },
  {
    id: "mistral",
    name: "Mistral",
    company: "Mistral AI",
    desc: "High-performance open models from Mistral AI.",
    url: "https://chat.mistral.ai",
    color: "#FF7000",
    initials: "Mi",
    logo: "/assets/uploads/mistral-ai-019d21fe-c429-7319-bfe6-a36aae04a48d-1.webp",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    company: "Perplexity AI",
    desc: "AI-powered search — real-time answers with cited sources.",
    url: "https://www.perplexity.ai",
    color: "#20808D",
    initials: "Px",
    logo: "/assets/uploads/perplexity-ai-icon-019d21d9-5643-736a-b961-6c41c5664f43-4.webp",
  },
  {
    id: "copilot",
    name: "Copilot",
    company: "Microsoft",
    desc: "Microsoft's AI assistant — integrated intelligence for productivity.",
    url: "https://copilot.microsoft.com",
    color: "#0078D4",
    initials: "Co",
    logo: "/assets/uploads/copilot-icon-019d21d9-5682-7549-ab8d-7d11bccddb03-5.webp",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    company: "DeepSeek",
    desc: "DeepSeek's frontier model — cutting-edge reasoning and coding.",
    url: "https://chat.deepseek.com",
    color: "#4D6AF0",
    initials: "Ds",
    logo: "/assets/uploads/deepseek-logo-icon-019d21d9-5693-71e0-86e9-05ce2cc5429d-7.webp",
  },
  {
    id: "grok-regular",
    name: "Grok",
    company: "xAI",
    desc: "Built by xAI — helpful, truthful, and maximum truth-seeking.",
    url: "https://grok.x.ai",
    color: "#1DA1F2",
    initials: "Gk",
    logo: "/assets/uploads/grok-icon-019d21d9-5779-724d-b918-b3fab4175467-8.webp",
  },
  {
    id: "caffeine-ai",
    name: "Caffeine.ai",
    company: "On ICP",
    desc: "Build full-stack decentralized AI apps on the Internet Computer by chatting.",
    url: "https://caffeine.ai",
    color: "#CCFF00",
    initials: "Ca",
    logo: "/assets/uploads/caffeineai-019d2eec-e466-748a-a5a7-c8d30234a018-1.jpg",
  },
  // Music Generation
  {
    id: "suno",
    name: "Suno",
    company: "Suno AI",
    desc: "Full song AI music creation with lyrics and vocals.",
    url: "https://suno.com",
    color: "#FF6B6B",
    initials: "Su",
    logo: "/assets/uploads/sunologo-019d21fe-c535-72e8-aaea-e43a64ff701b-4.png",
  },
  {
    id: "udio",
    name: "Udio",
    company: "Udio",
    desc: "Creative AI music generator with realistic vocals and studio control.",
    url: "https://udio.com",
    color: "#A855F7",
    initials: "Ud",
    logo: "/assets/uploads/udio-019d21fe-c490-75b4-9ddd-4bc796830d15-2.png",
  },
  {
    id: "minimax-music",
    name: "Minimax Music",
    company: "Minimax AI",
    desc: "High-quality AI music and audiovisual generation.",
    url: "https://www.minimaxi.com/en/music",
    color: "#F59E0B",
    initials: "Mm",
    logo: "/assets/uploads/minimax-019d21fe-c4d1-73ba-9736-3bcc821a4309-3.webp",
  },
  // General / Multimodal
  {
    id: "qwen",
    name: "Qwen",
    company: "Alibaba",
    desc: "Powerful open multilingual model with strong reasoning and coding.",
    url: "https://chat.qwen.ai",
    color: "#7B61FF",
    initials: "Qw",
    logo: "/assets/uploads/qwen-ai-icon-019d21d9-564f-768a-b5d2-4e4f12379e76-6.png",
  },
  {
    id: "glm",
    name: "GLM-5",
    company: "Zhipu AI",
    desc: "Powerful frontier model from Zhipu AI with strong multimodal capabilities.",
    url: "https://chatglm.cn",
    color: "#FF6B35",
    initials: "GL",
    logo: "/assets/uploads/zai-019d246a-0f31-7248-a0e1-c26ed2e28f9d-1.webp",
  },
  // Coding / Agentic
  {
    id: "cursor",
    name: "Cursor",
    company: "Anysphere",
    desc: "AI-native code editor for autonomous coding and refactoring.",
    url: "https://cursor.com",
    color: "#22D3EE",
    initials: "Cu",
    logo: "/assets/uploads/cursor-ai-code-icon-019d21d9-5780-77db-bdff-420d391b1ad9-9.webp",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    company: "Anthropic",
    desc: "Claude optimized for software engineering and agentic coding.",
    url: "https://claude.ai",
    color: "#CC785C",
    initials: "CC",
    logo: "/assets/uploads/claudecode-color-019d246a-1038-71a1-8b04-516e094b66a0-6.webp",
  },
  // Image Generation
  {
    id: "midjourney",
    name: "Midjourney",
    company: "Midjourney",
    desc: "Best-in-class AI image generation with artistic control.",
    url: "https://midjourney.com",
    color: "#FFFFFF",
    initials: "MJ",
    logo: "/assets/uploads/midjourney-019d246a-0fa5-7722-bc2a-5651824f5957-3.webp",
  },
  {
    id: "flux",
    name: "FLUX",
    company: "Black Forest Labs",
    desc: "State-of-the-art open AI image generation from Black Forest Labs.",
    url: "https://blackforestlabs.ai",
    color: "#FF5722",
    initials: "FL",
    logo: "/assets/uploads/flux-019d246a-102b-70ed-8dd0-5f3780424b07-8.webp",
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    company: "Adobe",
    desc: "Creative AI image and design tools from Adobe.",
    url: "https://firefly.adobe.com",
    color: "#FF0000",
    initials: "AF",
    logo: "/assets/uploads/adobefirefly-019d246a-108b-77f2-98d5-781b7dc59240-10.webp",
  },
  // Video Generation
  {
    id: "runway",
    name: "Runway",
    company: "Runway ML",
    desc: "Advanced AI video generation and editing tools.",
    url: "https://runwayml.com",
    color: "#FFFFFF",
    initials: "RW",
    logo: "/assets/uploads/runway-019d246a-103d-761c-8572-0df7db867498-7.webp",
  },
  // Voice
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    company: "ElevenLabs",
    desc: "Industry-leading AI voice and audio generation.",
    url: "https://elevenlabs.io",
    color: "#FFFFFF",
    initials: "EL",
    logo: "/assets/uploads/elevenlabs-019d246a-0fb9-74fe-b41d-ecc0cce1cccb-4.webp",
  },
  // Developer Tools
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    company: "GitHub",
    desc: "AI pair programmer for code completion and generation.",
    url: "https://github.com/features/copilot",
    color: "#FFFFFF",
    initials: "GC",
    logo: "/assets/uploads/githubcopilot-019d246a-0f86-71dd-8c17-3ea46611a1fe-2.webp",
  },
  {
    id: "vercel",
    name: "Vercel",
    company: "Vercel",
    desc: "AI-powered frontend and full-stack development platform.",
    url: "https://vercel.com/ai",
    color: "#FFFFFF",
    initials: "VC",
    logo: "/assets/uploads/v0-019d246a-1032-766f-ad27-fc6b842da433-9.webp",
  },
  // Agentic
  {
    id: "manus",
    name: "Manus",
    company: "Manus AI",
    desc: "Advanced AI agent for complex tasks and reasoning.",
    url: "https://manus.im",
    color: "#FFFFFF",
    initials: "Mn",
    logo: "/assets/uploads/manus-text-019d246a-0fde-759e-a4fc-c5ce823ebf6e-5.webp",
  },
  // Multimodal / General
  {
    id: "kimi",
    name: "Kimi",
    company: "Moonshot AI",
    desc: "Powerful multimodal AI from Moonshot AI with strong reasoning.",
    url: "https://kimi.moonshot.cn",
    color: "#1A73E8",
    initials: "Ki",
    logo: "/assets/uploads/kimi-019d24e4-6d53-772e-9293-2f7a59afcd7d-1.webp",
  },
  // Coding
  {
    id: "codex",
    name: "Codex",
    company: "OpenAI",
    desc: "OpenAI's specialized coding model for software development.",
    url: "https://openai.com",
    color: "#10A37F",
    initials: "Cx",
    logo: "/assets/uploads/codex-019d24e4-6d7c-742b-88f5-763b811ebc3b-4.webp",
  },
  // Platform
  {
    id: "huggingface",
    name: "Hugging Face",
    company: "Hugging Face",
    desc: "The leading platform for open-source AI models and tools.",
    url: "https://huggingface.co",
    color: "#FFD21E",
    initials: "HF",
    logo: "/assets/uploads/huggingface-019d24e4-6e0e-72e7-ac6d-9fcb47218b42-7.webp",
  },
  // Video Generation
  {
    id: "kling",
    name: "Kling",
    company: "Kuaishou",
    desc: "High-quality AI video generation from Kuaishou.",
    url: "https://kling.ai",
    color: "#FF4081",
    initials: "Kl",
    logo: "/assets/uploads/kling-019d24e4-6dc4-7508-a87e-fbc965214f6d-6.webp",
  },
  // Image Generation
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    company: "Stability AI",
    desc: "Popular open-source AI image generation family.",
    url: "https://stability.ai",
    color: "#9C27B0",
    initials: "SD",
    logo: "/assets/uploads/stablediffusion-019d24e4-6d54-722e-8f75-7bf7a76d864f-3.webp",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    company: "Ideogram AI",
    desc: "Advanced AI image generation with excellent text rendering.",
    url: "https://ideogram.ai",
    color: "#1A73E8",
    initials: "Id",
    logo: "/assets/uploads/ideogram-019d24e4-6d49-72a4-813b-ff7234b14330-2.webp",
  },
  {
    id: "leonardo-ai",
    name: "Leonardo AI",
    company: "Leonardo AI",
    desc: "Creative AI image and video generation platform.",
    url: "https://leonardo.ai",
    color: "#FF6B35",
    initials: "LA",
    logo: "/assets/uploads/leonardoai.webp-019d24e4-6fb3-73b1-9190-23b867f8900a-8.png",
  },
  // Research
  {
    id: "notebooklm",
    name: "NotebookLM",
    company: "Google",
    desc: "Google's AI-powered research and note-taking assistant.",
    url: "https://notebooklm.google",
    color: "#4285F4",
    initials: "NL",
    logo: "/assets/uploads/notebooklm-019d24e4-6da3-757f-b07e-f8e0b911870f-5.webp",
  },
  // Image & Creative Tools
  {
    id: "dalle",
    name: "DALL·E",
    company: "OpenAI",
    desc: "Powerful AI image generation from OpenAI.",
    url: "https://chat.openai.com",
    color: "#10A37F",
    initials: "DE",
    logo: "/assets/uploads/dalle-019d2f79-cdaa-74b6-b20b-b974aead965c-1.webp",
  },
  {
    id: "nano-banana",
    name: "Nano Banana",
    company: "Nano Banana",
    desc: "Fun and creative AI image generation tool.",
    url: "https://gemini.google/overview/image-generation/",
    color: "#FFD700",
    initials: "NB",
    logo: "/assets/uploads/nanobanana-019d2f79-cddc-7148-9ef8-372cc973864c-2.webp",
  },
  {
    id: "replicate",
    name: "Replicate",
    company: "Replicate",
    desc: "Run and deploy open-source AI models in the cloud.",
    url: "https://replicate.com",
    color: "#ffffff",
    initials: "RE",
    logo: "/assets/uploads/replicate-019d2f79-ce14-7688-b953-f23e8a399799-3.webp",
  },
  {
    id: "ai-studio-google",
    name: "AI Studio",
    company: "Google",
    desc: "Google's platform for building and experimenting with AI.",
    url: "https://aistudio.google.com",
    color: "#4285F4",
    initials: "AS",
    logo: "/assets/uploads/aistudio-019d2f79-ce3c-750f-accf-4f6d332df241-4.webp",
  },
  {
    id: "anti-gravity",
    name: "Anti-Gravity",
    company: "Anti-Gravity",
    desc: "Innovative AI tools and creative generation platform.",
    url: "https://antigravity.google/",
    color: "#A855F7",
    initials: "AG",
    logo: "/assets/uploads/antigravity-019d2f79-ced4-74fa-94cd-d6b40af93052-5.webp",
  },
];

export const GROK_LOGO =
  "/assets/uploads/grok-icon-019d21d9-5779-724d-b918-b3fab4175467-8.webp";
export const GROK_FALLBACK = "https://lobehub.com/icons/grok.svg";

export const OS_CATEGORIES: { id: OSCategory; label: string }[] = [
  { id: "text", label: "Text-to-Text" },
  { id: "image", label: "Image Generation" },
  { id: "video", label: "Video Generation" },
  { id: "voice", label: "Voice Generation" },
  { id: "small", label: "Small & Micro" },
];

export const OS_MODELS: Record<OSCategory, OSModel[]> = {
  text: [
    {
      id: "deepseek-v3",
      name: "DeepSeek V3.2",
      developer: "DeepSeek AI",
      desc: "Math and reasoning king with MoE architecture.",
      specs: "685B MoE • Reasoning leader",
      hfUrl: "https://huggingface.co/deepseek-ai/DeepSeek-V3",
      githubUrl: "https://github.com/deepseek-ai/DeepSeek-V3",
      color: "#4D6AF0",
      initials: "DS",
    },
    {
      id: "qwen35",
      name: "Qwen 3.5",
      developer: "Alibaba",
      desc: "Massive multilingual MoE with top reasoning capabilities.",
      specs: "397B MoE • Multilingual",
      hfUrl: "https://huggingface.co/Qwen",
      githubUrl: "https://github.com/QwenLM/Qwen3",
      color: "#7B61FF",
      initials: "Q3",
    },
    {
      id: "llama4",
      name: "Llama 4",
      developer: "Meta",
      desc: "Meta's latest open-weight multimodal powerhouse.",
      specs: "405B • Multimodal",
      hfUrl: "https://huggingface.co/meta-llama",
      githubUrl: "https://github.com/meta-llama",
      color: "#0081FB",
      initials: "L4",
    },
    {
      id: "glm5",
      name: "GLM-5",
      developer: "Z.ai",
      desc: "Largest open-weights model with strong multilingual coding.",
      specs: "744B • Multilingual coding",
      hfUrl: "https://huggingface.co/THUDM",
      githubUrl: "https://github.com/THUDM",
      color: "#FF6B35",
      initials: "G5",
    },
    {
      id: "deepseek-r1",
      name: "DeepSeek R1",
      developer: "DeepSeek AI",
      desc: "Pure reasoning specialist with chain-of-thought excellence.",
      specs: "671B MoE • Reasoning specialist",
      hfUrl: "https://huggingface.co/deepseek-ai/DeepSeek-R1",
      githubUrl: "https://github.com/deepseek-ai/DeepSeek-R1",
      color: "#4D6AF0",
      initials: "R1",
    },
  ],
  image: [
    {
      id: "flux1dev",
      name: "FLUX.1 Dev",
      developer: "Black Forest Labs",
      desc: "Top open-source image gen with incredible detail and accuracy.",
      specs: "12B • State-of-the-art quality",
      hfUrl: "https://huggingface.co/black-forest-labs/FLUX.1-dev",
      githubUrl: "https://github.com/black-forest-labs/flux",
      color: "#FF5722",
      initials: "F1",
    },
    {
      id: "sd35large",
      name: "SD 3.5 Large",
      developer: "Stability AI",
      desc: "Professional 8B flagship for production-grade image generation.",
      specs: "8B • Professional flagship",
      hfUrl: "https://huggingface.co/stabilityai/stable-diffusion-3.5-large",
      githubUrl: "https://github.com/Stability-AI/generative-models",
      color: "#9C27B0",
      initials: "SD",
    },
    {
      id: "flux1kontext",
      name: "FLUX.1 Kontext",
      developer: "Black Forest Labs",
      desc: "Advanced in-context editing with deep contextual understanding.",
      specs: "Context editing • Advanced",
      hfUrl: "https://huggingface.co/black-forest-labs/FLUX.1-Kontext-dev",
      githubUrl: "https://github.com/black-forest-labs/flux",
      color: "#FF5722",
      initials: "FK",
    },
    {
      id: "qwenimg",
      name: "Qwen-Image",
      developer: "Alibaba",
      desc: "Versatile image editing and generation in one unified model.",
      specs: "Editing + Generation • Versatile",
      hfUrl: "https://huggingface.co/Qwen",
      githubUrl: "https://github.com/QwenLM",
      color: "#7B61FF",
      initials: "QI",
    },
  ],
  video: [
    {
      id: "wan22",
      name: "Wan 2.2",
      developer: "Alibaba",
      desc: "MoE cinematic text-to-video leader with stunning quality.",
      specs: "MoE • Cinematic text-to-video",
      hfUrl: "https://huggingface.co/Wan-AI",
      githubUrl: "https://github.com/Wan-Video/Wan2.1",
      color: "#FF6B35",
      initials: "W2",
    },
    {
      id: "hunyuan15",
      name: "HunyuanVideo 1.5",
      developer: "Tencent",
      desc: "High-quality open video model with exceptional detail.",
      specs: "8.3B • High-quality open model",
      hfUrl: "https://huggingface.co/tencent/HunyuanVideo",
      githubUrl: "https://github.com/Tencent/HunyuanVideo",
      color: "#00B4D8",
      initials: "HV",
    },
    {
      id: "mochi",
      name: "Mochi",
      developer: "Genmo",
      desc: "Fast and creative open video diffusion model.",
      specs: "10B • Fast creative diffusion",
      hfUrl: "https://huggingface.co/genmo/mochi-1-preview",
      githubUrl: "https://github.com/genmoai/mochi",
      color: "#4CAF50",
      initials: "Mo",
    },
  ],
  voice: [
    {
      id: "fishspeech",
      name: "Fish Speech V1.5",
      developer: "Fish Audio",
      desc: "Multilingual top-tier voice synthesis quality.",
      specs: "Multilingual • Top-tier quality",
      hfUrl: "https://huggingface.co/fishaudio/fish-speech-1.5",
      githubUrl: "https://github.com/fishaudio/fish-speech",
      color: "#26C6DA",
      initials: "FS",
    },
    {
      id: "cosyvoice2",
      name: "CosyVoice 2",
      developer: "Alibaba",
      desc: "Ultra-low latency real-time voice synthesis.",
      specs: "Ultra-low latency • Real-time",
      hfUrl: "https://huggingface.co/FunAudioLLM/CosyVoice2-0.5B",
      githubUrl: "https://github.com/FunAudioLLM/CosyVoice",
      color: "#7B61FF",
      initials: "CV",
    },
    {
      id: "kokoro",
      name: "Kokoro 82M",
      developer: "Hexgrad",
      desc: "Tiny but powerful on-device TTS model.",
      specs: "82M params • On-device TTS",
      hfUrl: "https://huggingface.co/hexgrad/Kokoro-82M",
      githubUrl: "https://github.com/hexgrad/kokoro",
      color: "#FF8A65",
      initials: "Ko",
    },
    {
      id: "mosstts",
      name: "MOSS-TTS Family",
      developer: "MOSS AI",
      desc: "Expressive long-form synthesis with voice cloning support.",
      specs: "Expressive • Long-form + Cloning",
      hfUrl: "https://huggingface.co/fnlp",
      githubUrl: "https://github.com/OpenMOSS",
      color: "#66BB6A",
      initials: "MT",
    },
  ],
  small: [
    {
      id: "phi4mini",
      name: "Phi-4 Mini",
      developer: "Microsoft",
      desc: "3.8B model that runs efficiently on phones and edge devices.",
      specs: "3.8B • Runs on phones",
      hfUrl: "https://huggingface.co/microsoft/Phi-4-mini-instruct",
      githubUrl: "https://github.com/microsoft/Phi-4-mini",
      color: "#0078D4",
      initials: "P4",
    },
    {
      id: "gemma3",
      name: "Gemma 3",
      developer: "Google",
      desc: "Multimodal edge AI champion for on-device deployment.",
      specs: "9B/27B • Multimodal edge king",
      hfUrl: "https://huggingface.co/google/gemma-3-27b-it",
      githubUrl: "https://github.com/google-deepmind/gemma",
      color: "#4285F4",
      initials: "G3",
    },
    {
      id: "qwen35small",
      name: "Qwen 3.5 Small",
      developer: "Alibaba",
      desc: "Efficient multilingual small variants for resource-constrained environments.",
      specs: "Efficient • Multilingual variants",
      hfUrl: "https://huggingface.co/Qwen",
      githubUrl: "https://github.com/QwenLM/Qwen3",
      color: "#7B61FF",
      initials: "QS",
    },
  ],
};

export const NAV_ITEMS: { label: string; page: Page }[] = [
  { label: "Home", page: "home" },
  { label: "Open Source Models", page: "open-source" },
  { label: "Onchain AI Models", page: "onchain" },
  { label: "Benchmarks", page: "benchmarks" },
  { label: "About", page: "about" },
];
